version: "3"
services:
  ocr-api:
    build:
      context: ""
      dockerfile: Dockerfile
    image: "ocr-api"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    ports:
      - 8000:8000
    restart: on-failure